# Generated by Django 4.0.4 on 2022-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.TextField()),
                ('title', models.TextField()),
                ('authors', models.JSONField(default=list)),
                ('published_year', models.CharField(max_length=4)),
                ('acquired', models.BooleanField(default=False)),
                ('thumbnail', models.TextField(max_length=450)),
            ],
        ),
    ]
